### ISSUE TITLE
harmonize returned values for `lambda`

### ISSUE THREAD

**Issue by wpetry** [levisc8/ipmr#27]
I find it confusing that `lambda` returns λ when `type_lambda = 'all'` and `type_lambda = 'last'`, but returns log(λ) for `type_lambda = 'stochastic'`. I suggest adding a logical argument `log` that allows the user to toggle between these scales. Given the function name `lambda`, I think it would be most natural to set `log = FALSE` as the default.

**Comment by levisc8** [comment]
Hi @wpetry - I thought it was pretty standard to use log `lambda` for stochastic models. Is that not the case?

Would `mean(n_t_1/n_t)` as the default for stochastic lambda make more sense then?
