### ISSUE TITLE
`make_ipm()` errors when `sample_env()` draws only one param

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#28]
If you take the "modeling the environment directly" example from the introduction vignette and edit it so only `temp` is a covariate,`make_ipm()` gives the following error:

```
#> rlang::last_trace()
<error/purrr_error_bad_element_type>
Element 2 of `.x` must be a vector, not a function
Backtrace:
    █
 1. ├─`%>%`(...)
 2. ├─ipmr::make_ipm(...)
 3. ├─ipmr:::make_ipm.simple_di_stoch_param(...)
 4. │ └─ipmr:::.bind_all_constants(...)
 5. │   ├─.flatten_to_depth(env_state, 1) %>% .[!duplicated(names(.))]
 6. │   └─ipmr:::.flatten_to_depth(env_state, 1)
 7. │     └─purrr::flatten(to_flatten)
 8. └─purrr:::stop_bad_element_type(...)
 9.   └─purrr:::stop_bad_type(...)
```

All I did was remove precip from the formulae in `define_kernel()` so they are:

```
    g_mu    = g_int + g_slope * surf_area_1 + g_temp * temp,
    s_lin_p = s_int + s_slope * surf_area_1 + s_temp * temp,
```

And change `env_states` to :

```
env_states <- data.frame(temp = rnorm(10, mean = 8.9, sd = 1.2))

```

**Comment by levisc8** [comment]
Thanks for bringing this to my attention - I think it's related to #22, so I'll try to get this shortly!

**Comment by Aariq** [comment]
I tried it a different way by putting the `sample_env()` function in `make_ipm(usr_funs = list(sample_env = sample_env)`, but now running `make_ipm()` I get `Error in sample_env(env_states = env_states, t) : 
  object 'env_states' not found`.  `env_states` is in the `data_list()` for `define_env_state()` and exists in the environment.

**Comment by levisc8** [comment]
So the last commit _should_ address the issue you raised - can you try with the development version and let me know how that goes?

**Comment by Aariq** [comment]
Yeah, that works now, at least with the modified example.

**Comment by levisc8** [comment]
ok, thanks again for bringing this up! closing this now, but feel free to re-open if you have a related problem
