### ISSUE TITLE
`define_env_state()` doesn't work properly with `predict()` method for vital rate function.

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#29]
If I use `predict()` to define a vital rate function and include an environmental covariate in `newdata`, I get an error in `model.frame.default()`.

### A contrived example:

Starting with the example IPM from [this section](https://levisc8.github.io/ipmr/articles/ipmr-introduction.html#pre-determined-sequences-of-environmental-covariates-1) of the intro vignette, I fit a model with survival as a function of (randomly generated) precip.

```
data("iceplant_ex")
library(tidyverse)
iceplant_ex <- iceplant_ex %>% add_column(precip = rgamma(nrow(.), shape = 1000, rate = 2))
surv_mod <- glm(survival ~ size + precip, data = iceplant_ex, family = binomial())
```

I added `surv_mod` to `constant_params` and replaced `s_lin_p`  with 
```
    s_lin_p = predict(surv_mod, newdata = list(size = surf_area_1, precip = precip)),
```

Running `make_ipm()` on this modified example gives the error:
```
Error in model.frame.default(Terms, newdata, na.action = na.action, xlev = object$xlevels) : variable lengths differ (found for 'precip')
```

Traceback:
![Screen Shot 2021-07-15 at 1 35 37 PM](https://user-images.githubusercontent.com/25404783/125832193-0abe7702-fd1f-491f-bf63-4b451a89920a.png)

**Comment by levisc8** [comment]
I think if you change `newdata = list(...)` to `newdata = data.frame(....)`, it should solve the problem. `list` won't recycle the value of precip, whereas `data.frame` will. This worked for me using the development version, but let me know if it's still an issue for you.

**Comment by Aariq** [comment]
Yup! This worked.  Thanks!
