### ISSUE TITLE
uninformative error when iteration matrix is all NAs

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#34]
I'm not sure what I did to cause this error when running `make_ipm()` yet, but I tracked it to this line of code with `debug()`.  
https://github.com/levisc8/ipmr/blob/17a3db21391be33d793402592e66c7833342e097/R/internal-make_ipm.R#L1301
`mat` is all NAs so `any(mat < 0)` returns `NA` and the `if()` errors with:

```
Error in if (any(mat < 0)) { : missing value where TRUE/FALSE needed
```

I'm guessing my all-NA iteration matrix shouldn't have even existed and it should have errored earlier.  If I figure out what I did wrong, I'll reply here.

**Comment by Aariq** [comment]
Ah, I think it was because my `env_states` dataframe had a row with all `NAs`, so I'm guessing the result of `predict()` was also all `NAs`.  Might be good to check for `NA`s earlier?

**Comment by levisc8** [comment]
Hi @Aariq - I think the above-referenced commit should handle this issue so I'm going to close it for now. Feel free to re-open if you find it inadequate/something related comes up.
