### ISSUE TITLE
`right_ev()` does not scale population state correctly (colSums !=1)

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#37]
https://github.com/levisc8/ipmr/blob/6dd0e718eb47960cfc6d66a865a4cb86a9e38fa2/R/generics.R#L2041

This doesn't result in columns summing to 1 like it is intended to.  For example:

``` r
x <- matrix(c(rnorm(5), rnorm(5, 10), rnorm(5, 100)), ncol = 3)
out1 <- x/colSums(x)

out2 <- x
for(i in 1:ncol(x)) {
  out2[,i] <- x[,i]/sum(x[,i])
}
#test
colSums(out1) == 1
#> [1] FALSE FALSE FALSE

colSums(out2) == 1
#> [1] TRUE TRUE TRUE
```

This results in wonky looking state distributions when using `right_ev()`, at least for `simple_di_stoch_param` models.  Haven't checked other IPM types.

**Comment by Aariq** [comment]
A more concise solution than the for loop:
```
sweep(x, 2, colSums(x), "/")
```

**Comment by levisc8** [comment]
Thanks for the heads up! working on this now

**Comment by levisc8** [comment]
Try out the latest commit - I believe it should fix the problem. I do need to check the rest of the package for that behavior though...

**Comment by Aariq** [comment]
That looks much better.  Thanks for the speedy fix!

**Comment by levisc8** [comment]
Great, closing now. Feel free to reopen if you notice anything wonky though!
