### ISSUE TITLE
log(mean(lambdas)) ≠ mean(log(lambdas))

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#41]
When calculating stochastic lambda, the outputs of these two lines are not the same and it seems like they should be.
```
lambda(ipm, type_lambda = "stochastic", log = TRUE)
log(lambda(ipm, type_lambda = "stochastic", log = FALSE))
```
This is because the mean of all log-lambdas is not the same as the log of the mean of all lambdas

I think maybe `.thin_stoch_lambda()` should be something like:

```
.thin_stoch_lambda <- function(lambdas, burn_ind, log) {

  if(length(burn_ind > 0)) {
    out <- mean(lambdas[-c(burn_ind)])
  } else {
    out <- mean(lambdas)
  }
  if(log) out <- log(out)
  return(out)
}
```

**Comment by levisc8** [comment]
so the current code is basically what  you have in the second post (except applies to the conditional to the log transformation, rather than add the exp() step). 

```
if(log) lambdas <- log(lambdas)

  if(length(burn_ind > 0)) {
    out <- mean(lambdas[-c(burn_ind)])
  } else {
    out <- mean(lambdas)
  }
```

I wouldn't expect the first example to be the same as the log'ing should take place before applying the mean. Does that help at all?
