### ISSUE TITLE
Check for convergence in *stochastic* lambda?

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#42]
### Discussed in https://github.com/levisc8/ipmr/discussions/40

<div type='discussions-op-text'>

<sup>Originally posted by **Aariq** October  6, 2021</sup>
Right now it seems like it doesn't make sense to use `conv_plot()` or `is_conv_to_asymptotic()` on stochastic IPMs since both functions use the lambdas for each transition year.  I'm not super familiar with the literature on this, but it makes intuitive sense to me that you'd want to check for convergence in the *stochastic* lambda.  Couldn't you do this by checking for convergence after calculating a cumulative mean of log-lambda?</div>

**Comment by levisc8** [comment]
closed by #46
