### ISSUE TITLE
in `lambda()` on stochastic IPMs, `log = TRUE` has no effect for `type_lambda = 'last'` or `'all'`

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#43]
When running `lambda()` on a stochastic IPM, the `log` argument has no effect on the lambdas returned for "last" or "all".  To be consistent, it seems like it should have an effect.  If you have an idea for the desired behavior (e.g. log all `type_lambda` options for stochastic models by default, or log only when `type_lambda = "stochastic"`), I could make a small PR with a fix.

**Comment by Aariq** [comment]
This also affects the `log` argument to `conv_plot()` with stochastic IPMs.  Only the text and the location of the stable line changes.

**Comment by levisc8** [comment]
Hadn't noticed this, but checking the implementation I see why now :/ 

I'm fairly busy w/ other projects and so would welcome a PR! Thanks for pointing this out!

**Comment by levisc8** [comment]
closed by #44
