### ISSUE TITLE
env_seq gets unlnisted recursively

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#53]
This is maybe a weird edge case, but I have vital rates models that are GAMs that take a data frame with matrix columns.  Because the `proto_ipm$env_seq` gets unlisted recursively (the default for `unlist()`) the output doesn't look like the input.  For example, if my `sample_env()` function outputs something like this for a single iteration:

```
sample_env(data_full %>% select(spei_history), 1)
$spei_history
          [,1]       [,2]      [,3]      [,4]     [,5]      [,6]     [,7]      [,8]      [,9]    [,10]     [,11]
[1,] -1.331478 -0.8566401 -1.000386 -1.313495 -1.63653 -2.024821 -2.25552 -1.780731 -1.232011 0.163645 0.9614435
        [,12]     [,13]      [,14]     [,15]       [,16]     [,17]     [,18]     [,19]     [,20]     [,21]
[1,] 1.440836 0.6301332 -0.2844098 -0.252915 -0.08826031 0.5890239 0.2877022 0.9476817 0.8315037 0.9577722
        [,22]   [,23]   [,24]    [,25]    [,26]    [,27]    [,28]     [,29]      [,30]      [,31]     [,32]
[1,] 1.908109 1.75287 2.26437 1.412641 2.083237 1.194112 1.146075 -0.286554 -0.1933357 -0.1651673 0.2588008
         [,33]     [,34]      [,35]     [,36]     [,37]
[1,] 0.1826453 0.2680286 -0.8562538 -1.315719 -1.640294

```

Then the ipm$env_seq looks something like:
```
> ipm_dlnm_ff$env_seq 
  t spei_history1 spei_history2 spei_history3 spei_history4 spei_history5 spei_history6  ... spei_history37
1 1     0.2103302     0.3759758     0.8460177     0.7169548     0.9293107   -0.03144605  ... -0.08102309
2 2     0.9858378     0.5718160    -0.7310837    -1.3254078    -1.3687049   -1.63126382  ... -2.08027721
3 3    -1.2166994    -1.2700957     0.8460177     0.7169548     0.9293107   -0.03144605  ... -0.08102309
```

I've convinced myself it's not causing any problems in the actual IPM, the matrix just gets unlisted by this line I think:

https://github.com/levisc8/ipmr/blob/053fb52210e325209f64056c9a3a82b98312d7a2/R/internal-make_ipm.R#L544

Looks like it would probably break a bunch of stuff if this was changed to `unlist(recursive=FALSE)`, but I thought I'd let you know.  I got worried for a second when I realized that the input and output didn't quite match.

**Comment by Aariq** [comment]
No, sorry, disregard the actual numbers.  The thing that threw me off was I am providing a matrix called `spei_history` to `define_env_state()` and getting back a dataframe with columns `spei_history1` through `spei_history37` from `ipm$env_seq`

**Comment by levisc8** [comment]
Ah ok. The flattening won't happen before calling `predict` because it's just used to extract the values from the evaluation environment afterward evaluation. I do concede that the output format switching may not be ideal, but it is does provide consistent output (at least within `stoch_param` models), which I think is more important in the long run.

**Comment by Aariq** [comment]
Yeah, that makes sense!  I think it is probably rare that people will be passing matrices via `define_env_state()`

**Comment by levisc8** [comment]
I honestly hadn't thought about that possibility when I was designing the package. is there a reason that it can't be a `data.frame`? This is pretty new to me since I've never used `bam()`

**Comment by Aariq** [comment]
Because of the weird specifics of my data and methods, the data is in a matrix column in a tibble:

```
> data_full %>% select(ha_id_number, year, log_size, log_size_prev, spei_history) %>% head(3)
# A tibble: 3 × 5
  ha_id_number  year log_size log_size_prev spei_history[,1]   [,2]   [,3]    [,4]   [,5]    [,6]
  <fct>        <dbl>    <dbl>         <dbl>            <dbl>  <dbl>  <dbl>   <dbl>  <dbl>   <dbl>
1 1             1998     3.69         NA              -1.33  -0.857 -1.00  -1.31   -1.64  -2.02  
2 1             1999     3.09          3.69            1.35   0.965 -0.538 -0.0861 -0.568  1.07  
3 1             2000     3.87          3.09            0.169 -0.437 -0.702 -0.0499  0.490 -0.0246
> class(data_full$spei_history)
[1] "matrix" "array" 
```

Every observation (row) is associated with the past 36 months of SPEI and that goes into a GAM that fits a distributed lag non-linear model (DLNM) like so:

```
#e.g. for survival
gam(
    surv ~ s(log_size_prev) + te(spei_history, L),
    family = binomial,
    data = data_full
  )
```
Where L is another matrix-column indicating the lags 0:36. So survival is a (non-linear) function of size and the previous 36 months of SPEI. Working with matrix-columns has led me to find a whole bunch of bugs because it's such a weird corner case (not even common for GAMs).  There's maybe another way to store the data or parameterize the GAM, but I don't plan on changing at this point.

Like I said, this is probably a very **uncommon** use of `ipmr` and this is such a minor issue, so I wouldn't worry about it.  I mostly wanted to confirm that the flattening was happening *after* the important bits!

**Comment by Aariq** [comment]
The sub_kernels might also be messed up due to unflattening. I'm not sure.  I will eventually try to come up with a reprex for these GAM IPMs I'm doing.

<img width="948" alt="Screen Shot 2022-03-14 at 5 24 16 PM" src="https://user-images.githubusercontent.com/25404783/158263886-e11772f5-2c98-468f-b2d9-e21cd62329c6.png">

**Comment by levisc8** [comment]
That makes sense. It is good to know about that though, as I hadn't really considered the use of matrix columns _at all_ when developing the `stoch_param` code.

**Comment by levisc8** [comment]
Closing this, but feel free to reopen if you encounter related problems
