### ISSUE TITLE
`make_ipm()` hangs when `kernel_seq` is specified

### ISSUE THREAD

**Issue by Aariq** [levisc8/ipmr#58]
I'm iterating a general stochastic kernel sampled IPM and it hangs when I specify `kernel_seq`.  The vital rate models are GAMs with a random effect of `year` and in the IPM `predict()` is called with `newdata = data.frame(year = yr)` and `par_set_indices = list(yr = 2000:2009)`. I tracked the hanging down to this line of `.make_usr_seq()`:

https://github.com/levisc8/ipmr/blob/c40603ed76a53f58b7af09b2109823c9d826cf38/R/internal-make_ipm.R#L935

I don't understand why, but this call to `grepl()` is _incredibly_ slow for my IPM.  I don't quite understand what this line is doing or why it is so slow for my IPM but not noticeable for the one in the vignette. I assume there is a way to make this more efficient?

**Comment by Aariq** [comment]
Oh, the other problem with this line is that it's not looking through the unique values of `kernel_seq`.  Shouldn't it be
```
  for(i in seq_along(unique(kernel_seq))) {

    nms_test[i] <- any(grepl(unique(kernel_seq)[i], pos_ids$par_set_indices))

  }
```
?

**Comment by levisc8** [comment]
That is weird, I'll have to investigate that a bit more. How many iterations are you running it for?

**Comment by Aariq** [comment]
It completely hangs even with 10 iterations.  It seems like grepl() doesn't need to look through the entire proto_ipm to figure out if the values in kernel_seq are reasonable.

**Comment by levisc8** [comment]
Yea, I just looked at the code you linked and it is definitely wrong. I'll get to that next week.

**Comment by Aariq** [comment]
Is there any reason this wouldn't do the trick?
```
  for(i in seq_along(unique(kernel_seq))) {

    nms_test[i] <- any(grepl(unique(kernel_seq)[i], unlist(pos_ids$par_set_indices)))

  }
```
I assume that would be faster.

**Comment by Aariq** [comment]
Or ditch the for-loop entirely?
```
if(! all(unique(kernel_seq) %in% unique(pos_ids$par_set_indices)) {
stop("not all values of 'kern_seq' are present in the kernel names.  Please check the model definition.")
}
```

**Comment by levisc8** [comment]
Should be fixed in development version now, and am submitting to CRAN as I need a slew of updates for `Rpadrino` anyway. I'd suggest waiting til I've done all testing before downloading and using this for "real work". Going to close now, but please feel free to re-open if you still have problems with it.
