### ISSUE TITLE
plot simple ipm

### ISSUE THREAD

**Issue by PieterZuidema** [levisc8/ipmr#66]
Thanks @levisc8  for developing ipmr! I'll be using it in a course in Brazil later this month. 
I noted that the plot() function for a simple ipm (a simple_di_det_ipm) shows the plot for the F kernel only (I had an P and an F kernel in the ipm). The plot title is also "F". Does it take the last subkernel generated? How can I generate a plot of both kernels combined?

**Comment by levisc8** [comment]
Hi @PieterZuidema - glad to hear you're using `ipmr`! Sorry about that - the function was really designed for interactive use in Rstudio (where you can toggle through the plot list with the arrows). I've added two new arguments - `n_col` and `n_row` that function like `par(mfrow = c(n_row, n_col))` so you can put multiple plots on a single graphic device. I haven't tested it much, so please do let me know if it doesn't work the way you'd expect (feel free to reopen this issue)!

Hope the course goes well, and let me know if you encounter any other issues with the package!

**Comment by PieterZuidema** [comment]
Hi Sam

Thanks much. That certainly helps. I am using Rstudio but need to upday to get the toggle going I guess.

Cheers,

Pieter

Op 15 aug. 2022 om 10:22 heeft Sam Levin ***@***.***> het volgende geschreven:

﻿

Hi @PieterZuidema<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPieterZuidema&data=05%7C01%7Cpieter.zuidema%40wur.nl%7C46aff60467154bd17a8a08da7ec1295a%7C27d137e5761f4dc1af88d26430abb18f%7C0%7C0%7C637961665332027663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hTi3zgStd1lWGmEJLFWBAlCFLOBnRsvujl3EuyfbX4k%3D&reserved=0> - glad to hear you're using ipmr! Sorry about that - the function was really designed for interactive use in Rstudio (where you can toggle through the plot list with the arrows). I've added two new arguments - n_col and n_row that function like par(mfrow = c(n_row, n_col)) so you can put multiple plots on a single graphic device. I haven't tested it much, so please do let me know if it doesn't work the way you'd expect (feel free to reopen this issue)!

Hope the course goes well, and let me know if you encounter any other issues with the package!
